### ISSUE TITLE
Could not override border-bottom-color in .terminal-titlebar

### ISSUE THREAD

**Issue by khurshid-alam** [gnunn1/tilix#922]
I tried following code (with Numix): 

```css
.terminal-titlebar {
    border-bottom: 2px solid #f0544c;
}
```
It overrides with gtk inspector or if I put it ~/.config/gtk-3.0/gtk.css. But I can not make it override if I compile sass with this code.

I guess https://github.com/gnunn1/tilix/blob/master/data/resources/css/tilix.base.css#L157 prevents it from being overridden.
